name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint
        run: flake8 app ml tests --max-line-length=100

      - name: Train (smoke)
        env:
          MODEL_VERSION: ci
        run: python -m ml.train --out-dir artifacts --test-size 0.5

      - name: Run tests
        run: make test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/*
